name: calling workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: pulugarisanthosh25/reusableworkflow/.github/workflows/called-workflow.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
